routes/web.php
<?php
Route::get('sitemap.xml','App\Http\Controllers\SitemapController@index');
Route::get('/excel-cron', 'App\Http\Controllers\CronController@excel');
Route::get('/ajax/ajax-set-application-data/', 'App\Http\Controllers\AjaxController@setData')->name('ajax-application-store');
Route::post('/ajax/create-basket/', 'App\Http\Controllers\AjaxController@createBasket')->name('create-basket');
Route::post('/ajax/update-basket/', 'App\Http\Controllers\AjaxController@updateBasket')->name('update-basket');


Route::post('/iiyzicoSonuc', 'App\Http\Controllers\BasvuruController@iyzicoSonuc')->name('iyzicoSonuc');
Route::get('/online/{type}/{visitor?}/{search_id?}', 'App\Http\Controllers\BasvuruController@index')->name('basvuru');
Route::post('/online/{type}', 'App\Http\Controllers\BasvuruController@basvuruStore')->name('basvuru.store');
Route::post('/checkout/{type}', 'App\Http\Controllers\BasvuruController@basvuruStore')->name('basvuru.store');
Route::get('/iyzico', 'App\Http\Controllers\BasvuruController@payment')->name('iyzico');

Route::get('/', 'App\Http\Controllers\HomeController@index')->name('index');

Route::get('/marka-sonuc/{iletisimizni}/{marka}/{visitor}/{search_id}', 'App\Http\Controllers\HomeController@marka_sonuc')->name('marka-sonuc');

Auth::routes();

Route::get('/home', 'App\Http\Controllers\HomeController@welcome')->name('home');



Route::middleware(['auth'])->group(function () {
    Route::resource('/users', 'App\Http\Controllers\UserController');
    Route::resource('/companies', 'App\Http\Controllers\CompanyController');
    Route::resource('/searchs', 'App\Http\Controllers\SearchController');
    Route::resource('/customers', 'App\Http\Controllers\CustomerController');
    Route::resource('/web-pages', 'App\Http\Controllers\PageController');
    Route::resource('/product-classes', 'App\Http\Controllers\ProductClassController');
    Route::resource('/sectors', 'App\Http\Controllers\SectorController');
    Route::resource('/services', 'App\Http\Controllers\ServiceController');
    Route::resource('/packages', 'App\Http\Controllers\PackageController');
    Route::resource('/package-types', 'App\Http\Controllers\PackageTypeController');
    Route::resource('/categories', 'App\Http\Controllers\CategoryController');

    Route::get('/options', 'App\Http\Controllers\OptionController@index')->name('option.index');
    Route::post('/options', 'App\Http\Controllers\OptionController@save')->name('option.save');
    Route::get('/videos', 'App\Http\Controllers\VideoController@index')->name('videos.index');
    Route::post('/videos', 'App\Http\Controllers\VideoController@save')->name('video.save');

});


Route::get('/rehberler', 'App\Http\Controllers\HomeController@rehberler')->name('rehberler');

//Route::get('/icerik/{section}/{slug}', 'App\Http\Controllers\PageController@showPage')->name('show-page');
Route::get('/{slug}', 'App\Http\Controllers\PageController@showPage')->name('show-page');

app/Http/Controllers/ProductClassController.php
<?php

namespace App\Http\Controllers;

use App\Helpers\HashingSlug;
use App\Http\Requests\ProductClass\CreateProductClassRequest;
use App\Models\ProductClass;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class ProductClassController extends Controller
{


    public function index()
    {
        $product_classes = ProductClass::orderBy('name', 'ASC')->get();

        return view('product_classes.index', [
            'product_classes' => $product_classes
        ]);
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('product_classes.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateProductClassRequest $request)
    {
        try {
            $product_class = new ProductClass();
            $product_class->name = $request->name;
            $product_class->price = str_replace(',', '', $request->price);
            $product_class->save();
            return redirect(route('product-classes.index'))->with('success', 'Sınıf bilgileri başarılı bir şekilde sisteme eklenmiştir.');
        } catch(\Exception $ex) {
            return redirect(route('product-classes.index'))->with('danger', ' Güncelleme işlemi esnasında bir hata oluştu. Lütfen tekrar deneyiniz. <br/><pre> Hata:'.$ex->getMessage(). '</pre>');
        }


    }


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        dd('ss');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $id = HashingSlug::decodeHash($id);
        $product_class = ProductClass::find($id);
        if (!$product_class) {
            return back()->with('warning', 'İlgili kayıt bulunamamıştır. Lütfen kontrol ederek tekrar deneyiniz.');
        }

        return view('product_classes.edit', compact('product_class'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CreateProductClassRequest $request, $id)
    {

        $id = HashingSlug::decodeHash($id);
        $product_class = ProductClass::find($id);

        if (!$product_class) {
            return back()->with('warning', 'İlgili kayıt bulunamamıştır. Lütfen kontrol ederek tekrar deneyiniz.');
        }

        try {
            $product_class->name = $request->name;
            $product_class->price = str_replace(',', '', $request->price);
            $product_class->save();
        } catch(\Exception $ex) {
            return redirect(route('product-classes.index'))->with('danger', ' Güncelleme işlemi esnasında bir hata oluştu. Lütfen tekrar deneyiniz. <br/><pre> Hata:'.$ex->getMessage(). '</pre>');
        }
        return redirect(route('product-classes.index'))->with('success', 'Sınıf bilgileri başarılı bir şekilde sisteme güncellenmiştir.');


    }

    public function destroy($id) {

        $id = HashingSlug::decodeHash($id);
        $product_class = ProductClass::find($id);
        if (!$product_class) {
            return back()->with('warning', 'İlgili kayıt bulunamamıştır. Lütfen kontrol ederek tekrar deneyiniz.');
        }

        $product_class->forceDelete();


        return redirect(route('product-classes.index'))->with('success', 'Kayıt başarılı bir şekilde silinmiştir.');
    }
}

resources/views/product_classes/create.blade.php
@extends('layouts.app')
@section('title', 'Yeni Sınıf')
@section('content')
    <div class="content ">
        <br/>
        <!-- START CONTAINER FLUID -->
        <div class=" container-fluid   container-fixed-lg">
            <!-- START card -->
            {!! Form::open(['route' => 'product-classes.store','id'=>'admin-form','role'=>'form','autocomplete'=>'off', 'novalidate' => 'novalidate'])!!}
            <div class="card card-default">
                <div class="card-header ">
                    <div class="card-title">Sınıf
                    </div>
                    <div class="pull-right">
                        <button aria-label="" class="btn btn-success btn-icon-left m-b-10" type="submit"><i class="pg-icon">tick</i><span class=""> KAYDET</span></button>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="card-body">
                    @include('partials.alerts.error')
                    <p class="fs-16 mw-80 m-b-40">Platforma yeni sınıf eklemek için aşağıdaki formu doldurabilirsiniz. </p>
                    @include('product_classes.form')
                </div>
            </div>
            {!! Form::close() !!}
            <!-- END card -->
        </div>
        <!-- END CONTAINER FLUID -->
    </div>

@endsection
@section('scripts')


@endsection

resources/views/product_classes/edit.blade.php
@extends('layouts.app')
@section('title', 'Sınıf Düzenle')
@section('content')
    <div class="content ">
        <br/>
        <!-- START CONTAINER FLUID -->
        <div class=" container-fluid   container-fixed-lg">
            <!-- START card -->
            {!! Form::model($product_class,['method' => 'PATCH', 'route' => ['product-classes.update', createHashId($product_class->id)],'id'=>'admin-form','role'=>'form','autocomplete'=>'off', 'novalidate' => 'novalidate', 'files' => true])!!}
            <input type="hidden" name="q_id" value="{{ $product_class->id }}">
            <div class="card card-default">
                <div class="card-header ">
                    <div class="card-title">Sınıflar
                    </div>
                    <div class="pull-right">
                        <button aria-label="" class="btn btn-success btn-icon-left m-b-10" type="submit"><i class="pg-icon">tick</i><span class=""> GÜNCELLE</span></button>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="card-body">
                    @include('partials.alerts.error')
                    <p class="fs-16 mw-80 m-b-40">Platfordaki mevcut sınıfı güncellemek için aşağıdaki form üzerinde değişiklik yapabilirsiniz. </p>
                    @include('product_classes.form')
                </div>
            </div>
            {!! Form::close() !!}
            <!-- END card -->
        </div>
        <!-- END CONTAINER FLUID -->
    </div>

@endsection

@section('scripts')

@endsection

resources/views/product_classes/form.blade.php
<div class="row clearfix">
    <div class="col-xl-12">
        <div class="form-group form-group-default required">
            <label>Sınıf Adı</label>
            {!! Form::text("name",null,['class'=>'form-control','required'=>'required','id'=>'name']) !!}
        </div>
    </div>
</div>
<div class="row clearfix">
    <div class="col-xl-12">
        <div class="form-group form-group-default required">
            <label>Sınıf Ücreti</label>
            {!! Form::text("price",null,['class'=>'form-control','required'=>'required','id'=>'price']) !!}
        </div>
    </div>
</div>

resources/views/product_classes/index.blade.php
@extends('layouts.app')
@section('title', 'Sınıf Listeleri')
@section('content')
    <div class="content ">
        <br/>
        <!-- START CONTAINER FLUID -->
        <div class=" container-fluid   container-fixed-lg">
            <!-- START card -->
            <div class="card card-default">
                <div class="card-header ">
                    <div class="card-title">Sınıf Listeleri
                    </div>
                    <div class="pull-right">
                        <a aria-label="" href="{{ route('product-classes.create') }}" class="btn btn-success btn-icon-left m-b-10" type="button"><i class="pg-icon">plus</i><span class="">Yeni Sınıf Oluştur</span></a>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="card-body">
                    @include('partials.alerts.error')
                    <div class="table-responsive">
                        <table id="datatable" class="table table-bordered">
                            <thead>
                            <tr>
                                <th>Sınıf Adı</th>
                                <th>Fiyatı</th>
                                <th>İşlemler</th>
                            </tr>
                            </thead>


                            <tbody>
                            @foreach($product_classes as $product_class)
                            <tr>
                                <td>{{ $product_class->name }}</td>
                                <td>{{ str_replace('.00', '', $product_class->price) }}</td>

                                <td>
                                    <a href="{{ route('product-classes.edit', createHashId($product_class->id)) }}" aria-label=""  class="text-success">
                                        <span>Düzenle</span>
                                    </a>
                                    <a href="javascript:void(0);" onclick="return confirmOpsDelete('{{ createHashId($product_class->id) }}')" role="menuitem" class="text-danger">
                                        <i class="pg-trash"></i> Sil
                                    </a>
                                    {{ Form::open([
                                        'method' => 'DELETE',
                                        'url' => route("product-classes.destroy", createHashId($product_class->id)),
                                        'id' => 'ops-delete-form-' . createHashId($product_class->id)
                                        ]) }}
                                    {{ Form::close() }}


                                </td>

                            </tr>
                            @endforeach

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <!-- END card -->
        </div>
        <!-- END CONTAINER FLUID -->
    </div>

@endsection