routes/web.php
<?php
Route::get('sitemap.xml','App\Http\Controllers\SitemapController@index');
Route::get('/excel-cron', 'App\Http\Controllers\CronController@excel');
Route::get('/ajax/ajax-set-application-data/', 'App\Http\Controllers\AjaxController@setData')->name('ajax-application-store');
Route::post('/ajax/create-basket/', 'App\Http\Controllers\AjaxController@createBasket')->name('create-basket');
Route::post('/ajax/update-basket/', 'App\Http\Controllers\AjaxController@updateBasket')->name('update-basket');


Route::post('/iiyzicoSonuc', 'App\Http\Controllers\BasvuruController@iyzicoSonuc')->name('iyzicoSonuc');
Route::get('/online/{type}/{visitor?}/{search_id?}', 'App\Http\Controllers\BasvuruController@index')->name('basvuru');
Route::post('/online/{type}', 'App\Http\Controllers\BasvuruController@basvuruStore')->name('basvuru.store');
Route::post('/checkout/{type}', 'App\Http\Controllers\BasvuruController@basvuruStore')->name('basvuru.store');
Route::get('/iyzico', 'App\Http\Controllers\BasvuruController@payment')->name('iyzico');

Route::get('/', 'App\Http\Controllers\HomeController@index')->name('index');

Route::get('/marka-sonuc/{iletisimizni}/{marka}/{visitor}/{search_id}', 'App\Http\Controllers\HomeController@marka_sonuc')->name('marka-sonuc');

Auth::routes();

Route::get('/home', 'App\Http\Controllers\HomeController@welcome')->name('home');



Route::middleware(['auth'])->group(function () {
    Route::resource('/users', 'App\Http\Controllers\UserController');
    Route::resource('/companies', 'App\Http\Controllers\CompanyController');
    Route::resource('/searchs', 'App\Http\Controllers\SearchController');
    Route::resource('/customers', 'App\Http\Controllers\CustomerController');
    Route::resource('/web-pages', 'App\Http\Controllers\PageController');
    Route::resource('/product-classes', 'App\Http\Controllers\ProductClassController');
    Route::resource('/sectors', 'App\Http\Controllers\SectorController');
    Route::resource('/services', 'App\Http\Controllers\ServiceController');
    Route::resource('/packages', 'App\Http\Controllers\PackageController');
    Route::resource('/package-types', 'App\Http\Controllers\PackageTypeController');
    Route::resource('/categories', 'App\Http\Controllers\CategoryController');

    Route::get('/options', 'App\Http\Controllers\OptionController@index')->name('option.index');
    Route::post('/options', 'App\Http\Controllers\OptionController@save')->name('option.save');
    Route::get('/videos', 'App\Http\Controllers\VideoController@index')->name('videos.index');
    Route::post('/videos', 'App\Http\Controllers\VideoController@save')->name('video.save');

});


Route::get('/rehberler', 'App\Http\Controllers\HomeController@rehberler')->name('rehberler');

//Route::get('/icerik/{section}/{slug}', 'App\Http\Controllers\PageController@showPage')->name('show-page');
Route::get('/{slug}', 'App\Http\Controllers\PageController@showPage')->name('show-page');

app/Http/Controllers/PackageTypeController.php
<?php

namespace App\Http\Controllers;

use App\Helpers\HashingSlug;
use App\Http\Requests\PackageType\CreatePackageTypeRequest;
use App\Models\Basket;
use App\Models\Package;
use App\Models\PackageType;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class PackageTypeController extends Controller
{


    public function index()
    {
        $package_types = PackageType::orderBy('name', 'ASC')->get();

        return view('package_types.index', [
            'package_types' => $package_types
        ]);
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('package_types.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreatePackageTypeRequest $request)
    {
        try {
            $package_type = new PackageType();
            $package_type->name = $request->name;
            $package_type->slug = $request->slug;
            $package_type->description = $request->description;
            $package_type->icon = $request->icon;
            $package_type->active = $request->active;
            $package_type->save();
            return redirect(route('package-types.index'))->with('success', ' Paket türü bilgileri başarılı bir şekilde sisteme eklenmiştir.');
        } catch(\Exception $ex) {
            return redirect(route('package-types.index'))->with('danger', ' Güncelleme işlemi esnasında bir hata oluştu. Lütfen tekrar deneyiniz. <br/><pre> Hata:'.$ex->getMessage(). '</pre>');
        }


    }


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        dd('ss');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $id = HashingSlug::decodeHash($id);
        $package_type = PackageType::find($id);
        if (!$package_type) {
            return back()->with('warning', 'İlgili kayıt bulunamamıştır. Lütfen kontrol ederek tekrar deneyiniz.');
        }

        return view('package_types.edit', compact('package_type'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CreatePackageTypeRequest $request, $id)
    {

        $id = HashingSlug::decodeHash($id);
        $package_type = PackageType::find($id);

        if (!$package_type) {
            return back()->with('warning', 'İlgili kayıt bulunamamıştır. Lütfen kontrol ederek tekrar deneyiniz.');
        }

        try {
            $package_type->name = $request->name;
            $package_type->slug = $request->slug;
            $package_type->description = $request->description;
            $package_type->icon = $request->icon;
            $package_type->active = $request->active;
            $package_type->save();
        } catch(\Exception $ex) {
            return redirect(route('sectors.index'))->with('danger', ' Güncelleme işlemi esnasında bir hata oluştu. Lütfen tekrar deneyiniz. <br/><pre> Hata:'.$ex->getMessage(). '</pre>');
        }
        return redirect(route('package-types.index'))->with('success', 'Paket türü bilgileri başarılı bir şekilde sisteme güncellenmiştir.');


    }

    public function destroy($id) {

        $id = HashingSlug::decodeHash($id);
        $package_type = PackageType::find($id);
        if (!$package_type) {
            return back()->with('warning', 'İlgili kayıt bulunamamıştır. Lütfen kontrol ederek tekrar deneyiniz.');
        }


        $package = Package::where('package_type_id', $package_type->id)->first();
        if ($package) {
            return back()->with('warning', 'Türe ait paket tanımlaması bulunmaktadır. Paket silim ardından tekrar deneyiniz.');
        }
        $package = Package::where('package_type_id', $package_type->id)->first();
        if ($package) {
            return back()->with('warning', 'Türe ait paket tanımlaması bulunmaktadır. Paket silim ardından tekrar deneyiniz.');
        }
        $basket = Basket::where('package_type_id', $package_type->id)->first();
        if ($basket) {
            return back()->with('warning', 'Türe ait sepet tanımlaması bulunmaktadır. Sepet silim ardından tekrar deneyiniz.');
        }

        $package_type->forceDelete();






        return redirect(route('package-types.index'))->with('success', 'Kayıt başarılı bir şekilde silinmiştir.');
    }
}

resources/views/package_types/create.blade.php
@extends('layouts.app')
@section('title', 'Yeni Paket Türü')
@section('content')
    <div class="content ">
        <br/>
        <!-- START CONTAINER FLUID -->
        <div class=" container-fluid   container-fixed-lg">
            <!-- START card -->
            {!! Form::open(['route' => 'package-types.store','id'=>'admin-form','role'=>'form','autocomplete'=>'off', 'novalidate' => 'novalidate'])!!}
            <div class="card card-default">
                <div class="card-header ">
                    <div class="card-title">Paket türü
                    </div>
                    <div class="pull-right">
                        <button aria-label="" class="btn btn-success btn-icon-left m-b-10" type="submit"><i class="pg-icon">tick</i><span class=""> KAYDET</span></button>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="card-body">
                    @include('partials.alerts.error')
                    <p class="fs-16 mw-80 m-b-40">Platforma yeni paket türü eklemek için aşağıdaki formu doldurabilirsiniz. </p>
                    @include('package_types.form')
                </div>
            </div>
            {!! Form::close() !!}
            <!-- END card -->
        </div>
        <!-- END CONTAINER FLUID -->
    </div>

@endsection
@section('scripts')


@endsection

resources/views/package_types/edit.blade.php
@extends('layouts.app')
@section('title', 'Paket Türü Düzenle')
@section('content')
    <div class="content ">
        <br/>
        <!-- START CONTAINER FLUID -->
        <div class=" container-fluid   container-fixed-lg">
            <!-- START card -->
            {!! Form::model($package_type,['method' => 'PATCH', 'route' => ['package-types.update', createHashId($package_type->id)],'id'=>'admin-form','role'=>'form','autocomplete'=>'off', 'novalidate' => 'novalidate', 'files' => true])!!}
            <input type="hidden" name="q_id" value="{{ $package_type->id }}">
            <div class="card card-default">
                <div class="card-header ">
                    <div class="card-title">Paket Türleri
                    </div>
                    <div class="pull-right">
                        <button aria-label="" class="btn btn-success btn-icon-left m-b-10" type="submit"><i class="pg-icon">tick</i><span class=""> GÜNCELLE</span></button>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="card-body">
                    @include('partials.alerts.error')
                    <p class="fs-16 mw-80 m-b-40">Platfordaki mevcut paket türünü güncellemek için aşağıdaki form üzerinde değişiklik yapabilirsiniz. </p>
                    @include('package_types.form')
                </div>
            </div>
            {!! Form::close() !!}
            <!-- END card -->
        </div>
        <!-- END CONTAINER FLUID -->
    </div>

@endsection

@section('scripts')

@endsection

resources/views/package_types/form.blade.php
<div class="row clearfix">
    <div class="col-xl-4">
        <div class="form-group form-group-default">
            <label>Paket Türü Adı</label>
            {!! Form::text("name",null,['class'=>'form-control','required'=>'required','id'=>'name']) !!}
        </div>
    </div>
    <div class="col-xl-4">
        <div class="form-group form-group-default">
            <label>Paket Türü Bağlantısı</label>
            {!! Form::text("slug",null,['class'=>'form-control','required'=>'required','id'=>'slug']) !!}
        </div>
    </div>
    <div class="col-xl-4">
        <div class="form-group form-group-default required">
            <label>Durumu</label>
            {!! Form::select("active", ['1' => 'AKTİF', '0' => 'PASİF'], null, ['class'=>'form-control','id'=>'active']) !!}
        </div>
    </div>
</div>
<div class="row clearfix">
    <div class="col-xl-9">
        <div class="form-group form-group-default required">
            <label>Paket Türü Açıklaması</label>
            <textarea rows="2" cols="2" class='form-control  elastic editorezy'  id="description" name="description" >@if(isset($package_type)){!! $package_type->description !!}@elseif(!empty(old('description'))){!! old('description')  !!}@endif</textarea>
        </div>
    </div>
    <div class="col-xl-3">
        <div class="form-group form-group-default input-group">
            <div class="form-input-group">
                <label>Paket İkonu</label>
                {!!  Form::text('icon', null, ['required','class'=>'form-control','id'=>'icon'])!!}
            </div>
            <div class="input-group-append ">
              <span class="input-group-text"><a href="javascript:;" onclick="moxman.browse({extensions:'jpg,jpeg,png,gif,svg',fields: 'icon', no_host: true});" class="btn btn-info"><i class="glyphicon glyphicon-plus"></i> Ekle</a>
              </span>
            </div>
        </div>
    </div>
</div>

@push('scripts')
    <script>
        function slug(text) {
            var trMap = {
                'çÇ':'c',
                'ğĞ':'g',
                'şŞ':'s',
                'üÜ':'u',
                'ıİ':'i',
                'öÖ':'o'
            };
            for(var key in trMap) {
                text = text.replace(new RegExp('['+key+']','g'), trMap[key]);
            }
            return  text.replace(/[^-a-zA-Z0-9\s]+/ig, '') // remove non-alphanumeric chars
                .replace(/\s/gi, "-") // convert spaces to dashes
                .replace(/[-]+/gi, "-") // trim repeated dashes
                .toLowerCase();

        }

        $('#name').keyup(function () {
            var pageSlug = slug($('#name').val());
            $('#slug').val(pageSlug);
        });

    </script>
    @include('macros.editors')
@endpush

resources/views/package_types/index.blade.php
@extends('layouts.app')
@section('title', 'Paket Türü Listeleri')
@section('content')
    <div class="content ">
        <br/>
        <!-- START CONTAINER FLUID -->
        <div class=" container-fluid   container-fixed-lg">
            <!-- START card -->
            <div class="card card-default">
                <div class="card-header ">
                    <div class="card-title">Sektör Listeleri
                    </div>
                    <div class="pull-right">
                        <a aria-label="" href="{{ route('package-types.create') }}" class="btn btn-success btn-icon-left m-b-10" type="button"><i class="pg-icon">plus</i><span class="">Yeni Paket Türü Oluştur</span></a>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="card-body">
                    @include('partials.alerts.error')
                    <div class="table-responsive">
                        <table id="datatable" class="table table-bordered">
                            <thead>
                            <tr>
                                <th>Paket Türü</th>
                                <th>Bağlantı</th>
                                <th>İşlemler</th>
                            </tr>
                            </thead>


                            <tbody>
                            @foreach($package_types as $package_type)
                            <tr>
                                <td><img height="32px;" height="32px;" src="{!! $package_type->icon !!}"></td>
                                <td>{{ $package_type->name }}</td>
                                <td>{{ $package_type->slug }}</td>


                                <td>
                                    <a href="{{ route('package-types.edit', createHashId($package_type->id)) }}" aria-label=""  class="text-success">
                                        <span>Düzenle</span>
                                    </a>
                                    <a href="javascript:void(0);" onclick="return confirmOpsDelete('{{ createHashId($package_type->id) }}')" role="menuitem" class="text-danger">
                                        <i class="pg-trash"></i> Sil
                                    </a>
                                    {{ Form::open([
                                        'method' => 'DELETE',
                                        'url' => route("package-types.destroy", createHashId($package_type->id)),
                                        'id' => 'ops-delete-form-' . createHashId($package_type->id)
                                        ]) }}
                                    {{ Form::close() }}


                                </td>
                            </tr>
                            @endforeach

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <!-- END card -->
        </div>
        <!-- END CONTAINER FLUID -->
    </div>

@endsection