routes/web.php
<?php
Route::get('sitemap.xml','App\Http\Controllers\SitemapController@index');
Route::get('/excel-cron', 'App\Http\Controllers\CronController@excel');
Route::get('/ajax/ajax-set-application-data/', 'App\Http\Controllers\AjaxController@setData')->name('ajax-application-store');
Route::post('/ajax/create-basket/', 'App\Http\Controllers\AjaxController@createBasket')->name('create-basket');
Route::post('/ajax/update-basket/', 'App\Http\Controllers\AjaxController@updateBasket')->name('update-basket');


Route::post('/iiyzicoSonuc', 'App\Http\Controllers\BasvuruController@iyzicoSonuc')->name('iyzicoSonuc');
Route::get('/online/{type}/{visitor?}/{search_id?}', 'App\Http\Controllers\BasvuruController@index')->name('basvuru');
Route::post('/online/{type}', 'App\Http\Controllers\BasvuruController@basvuruStore')->name('basvuru.store');
Route::post('/checkout/{type}', 'App\Http\Controllers\BasvuruController@basvuruStore')->name('basvuru.store');
Route::get('/iyzico', 'App\Http\Controllers\BasvuruController@payment')->name('iyzico');

Route::get('/', 'App\Http\Controllers\HomeController@index')->name('index');

Route::get('/marka-sonuc/{iletisimizni}/{marka}/{visitor}/{search_id}', 'App\Http\Controllers\HomeController@marka_sonuc')->name('marka-sonuc');

Auth::routes();

Route::get('/home', 'App\Http\Controllers\HomeController@welcome')->name('home');



Route::middleware(['auth'])->group(function () {
    Route::resource('/users', 'App\Http\Controllers\UserController');
    Route::resource('/companies', 'App\Http\Controllers\CompanyController');
    Route::resource('/searchs', 'App\Http\Controllers\SearchController');
    Route::resource('/customers', 'App\Http\Controllers\CustomerController');
    Route::resource('/web-pages', 'App\Http\Controllers\PageController');
    Route::resource('/product-classes', 'App\Http\Controllers\ProductClassController');
    Route::resource('/sectors', 'App\Http\Controllers\SectorController');
    Route::resource('/services', 'App\Http\Controllers\ServiceController');
    Route::resource('/packages', 'App\Http\Controllers\PackageController');
    Route::resource('/package-types', 'App\Http\Controllers\PackageTypeController');
    Route::resource('/categories', 'App\Http\Controllers\CategoryController');

    Route::get('/options', 'App\Http\Controllers\OptionController@index')->name('option.index');
    Route::post('/options', 'App\Http\Controllers\OptionController@save')->name('option.save');
    Route::get('/videos', 'App\Http\Controllers\VideoController@index')->name('videos.index');
    Route::post('/videos', 'App\Http\Controllers\VideoController@save')->name('video.save');

});


Route::get('/rehberler', 'App\Http\Controllers\HomeController@rehberler')->name('rehberler');

//Route::get('/icerik/{section}/{slug}', 'App\Http\Controllers\PageController@showPage')->name('show-page');
Route::get('/{slug}', 'App\Http\Controllers\PageController@showPage')->name('show-page');

resources/views/pages/create.blade.php
@extends('layouts.app')
@section('title', 'Yeni Sayfa')
@section('content')
    <div class="content ">
        <br/>
        <!-- START CONTAINER FLUID -->
        <div class=" container-fluid   container-fixed-lg">
            <!-- START card -->
            {!! Form::open(['route' => 'web-pages.store','id'=>'admin-form','role'=>'form','autocomplete'=>'off', 'novalidate' => 'novalidate'])!!}
            <div class="card card-default">
                <div class="card-header ">
                    <div class="card-title">Sayfalar
                    </div>
                    <div class="pull-right">
                        <button aria-label="" class="btn btn-success btn-icon-left m-b-10" type="submit"><i class="pg-icon">tick</i><span class=""> KAYDET</span></button>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="card-body">
                    @include('partials.alerts.error')
                    <p class="fs-16 mw-80 m-b-40">Platforma yeni sayfa eklemek için aşağıdaki formu doldurabilirsiniz. </p>
                    @include('pages.form')
                </div>
            </div>
            {!! Form::close() !!}
            <!-- END card -->
        </div>
        <!-- END CONTAINER FLUID -->
    </div>

@endsection
@section('scripts')


@endsection

resources/views/pages/edit.blade.php
@extends('layouts.app')
@section('title', 'Sayfa Düzenle')
@section('content')
    <div class="content ">
        <br/>
        <!-- START CONTAINER FLUID -->
        <div class=" container-fluid   container-fixed-lg">
            <!-- START card -->
            {!! Form::model($page,['method' => 'PATCH', 'route' => ['web-pages.update', createHashId($page->id)],'id'=>'admin-form','role'=>'form','autocomplete'=>'off', 'novalidate' => 'novalidate', 'files' => true])!!}
            <input type="hidden" name="q_id" value="{{ $page->id }}">
            <div class="card card-default">
                <div class="card-header ">
                    <div class="card-title">Sayfalar
                    </div>
                    <div class="pull-right">
                        <button aria-label="" class="btn btn-success btn-icon-left m-b-10" type="submit"><i class="pg-icon">tick</i><span class=""> GÜNCELLE</span></button>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="card-body">
                    @include('partials.alerts.error')
                    <p class="fs-16 mw-80 m-b-40">Platfordaki mevcut sayfayı güncellemek için aşağıdaki form üzerinde değişiklik yapabilirsiniz. </p>
                    @include('pages.form')
                </div>
            </div>
            {!! Form::close() !!}
            <!-- END card -->
        </div>
        <!-- END CONTAINER FLUID -->
    </div>

@endsection

@section('scripts')

@endsection

resources/views/pages/form.blade.php
<div class="row clearfix">
    <div class="col-xl-3">
        <div class="form-group form-group-default required">
            <label>Sayfa Başlığı</label>
            {!! Form::text("title",null,['class'=>'form-control','required'=>'required','id'=>'title']) !!}
        </div>
    </div>
    <div class="col-xl-3">
        <div class="form-group form-group-default required">
            <label>Sayfa Bağlantısı</label>
            {!! Form::text("slug",null,['class'=>'form-control','required'=>'required','id'=>'slug']) !!}
        </div>
    </div>
    <div class="col-xl-3">
        <div class="form-group form-group-default form-group-default-select2">
            <label>Kategori</label>
            {!! Form::select("category_id", $categories , null, [ 'class'=>'full-width','id'=>'category_id','required'=>'required', 'data-init-plugin' => 'select2']) !!}
        </div>
    </div>
    <div class="col-xl-3">
        <div class="form-group form-group-default form-group-default-select2">
            <label>Durumu</label>
            {!! Form::select("active", [1 => 'AKTİF', 0 => 'PASİF'] , null, ['data-placeholder' => 'Durum seçiniz', 'class'=>'full-width','id'=>'active','required'=>'required', 'data-init-plugin' => 'select2']) !!}
        </div>
    </div>
</div>



<div class="row clearfix">
    <div class="col-xl-4">
        <div class="form-group form-group-default input-group">
            <div class="form-input-group">
                <label>Sayfa Görseli</label>
                {!!  Form::text('image', null, ['required','class'=>'form-control','readonly'=>'readonly','id'=>'image'])!!}
            </div>
            <div class="input-group-append ">
              <span class="input-group-text"><a href="javascript:;" onclick="moxman.browse({extensions:'jpg,jpeg,png,gif',fields: 'image', no_host: true});" class="btn btn-info"><i class="glyphicon glyphicon-plus"></i> Ekle</a>
              </span>
            </div>
        </div>
    </div>
    <div class="col-xl-4">
        <div class="form-group form-group-default input-group">
            <div class="form-input-group">
                <label>Sayfa Detay Görseli</label>
                {!!  Form::text('page_header_image', null, ['required','class'=>'form-control','readonly'=>'readonly','id'=>'page_header_image'])!!}
            </div>
            <div class="input-group-append ">
              <span class="input-group-text"><a href="javascript:;" onclick="moxman.browse({extensions:'jpg,jpeg,png,gif',fields: 'page_header_image', no_host: true});" class="btn btn-info"><i class="glyphicon glyphicon-plus"></i> Ekle</a>
              </span>
            </div>
        </div>
    </div>
    <div class="col-xl-4">
        <div class="form-group form-group-default form-group-default-select2">
            <label>Konumu</label>
            {!! Form::select("location", [3 => 'DEFAULT', 0 => 'SLİDER', 1 => 'ORTA BÖLÜM', 2 => 'TOPLU'] , null, ['data-placeholder' => 'Konum seçiniz', 'class'=>'full-width','id'=>'location','required'=>'required', 'data-init-plugin' => 'select2']) !!}
        </div>
    </div>
</div>
<div class="row clearfix">
    <div class="col-xl-12">
        <div class="form-group form-group-default required">
            <label>Sayfa Kısa İçerik</label>
            <textarea class="form-control" id="short_text" name="short_text" cols="50" rows="30"  style="height: 80px;" >{!! isset($page) ? $page->short_text : null !!}</textarea>
        </div>
    </div>
</div>

<div class="row clearfix">
    <div class="col-xl-12">
        <div class="form-group form-group-default required">
            <label>Sayfa İçeriği</label>
            <textarea rows="2" cols="4" class='form-control elastic editorezy'  id="page_content" name="page_content" >@if(isset($page)){!! $page->content !!}@elseif(!empty(old('content'))){!! old('content')  !!}@endif</textarea>
        </div>
    </div>
</div>
<div class="row clearfix">
    <div class="col-xl-6">
        <div class="form-group form-group-default required">
            <label>Meta Açıklama</label>
            <textarea class="form-control" id="metadescription" name="metadescription" cols="50" rows="30"  style="height: 80px;" >{!! isset($page) ? $page->metadescription : null !!}</textarea>
        </div>
    </div>
    <div class="col-xl-6">
        <div class="form-group form-group-default required">
            <label>Kelimeler</label>
            <textarea class="form-control" id="keywords" name="keywords" cols="50" rows="30"  style="height: 80px;" >{!! isset($page) ? $page->keywords : null !!}</textarea>
        </div>
    </div>
</div>
@push('scripts')
    @include('macros.editors')

    <script>
        function slug(text) {
            var trMap = {
                'çÇ':'c',
                'ğĞ':'g',
                'şŞ':'s',
                'üÜ':'u',
                'ıİ':'i',
                'öÖ':'o'
            };
            for(var key in trMap) {
                text = text.replace(new RegExp('['+key+']','g'), trMap[key]);
            }
            return  text.replace(/[^-a-zA-Z0-9\s]+/ig, '') // remove non-alphanumeric chars
                .replace(/\s/gi, "-") // convert spaces to dashes
                .replace(/[-]+/gi, "-") // trim repeated dashes
                .toLowerCase();

        }

        $('#title').keyup(function () {
            var pageSlug = slug($('#title').val());
            $('#slug').val(pageSlug);
        });

    </script>
@endpush

resources/views/pages/index.blade.php
@extends('layouts.app')
@section('title', 'Sayfa Listeleri')
@section('content')
    <div class="content ">
        <br/>
        <!-- START CONTAINER FLUID -->
        <div class=" container-fluid   container-fixed-lg">
            <!-- START card -->
            <div class="card card-default">
                <div class="card-header ">
                    <div class="card-title">Sayfalar
                    </div>
                    <div class="pull-right">
                        <a aria-label="" href="{{ route('web-pages.create') }}" class="btn btn-success btn-icon-left m-b-10" type="button"><i class="pg-icon">plus</i><span class="">Yeni Sayfa Oluştur</span></a>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="card-body">
                    @include('partials.alerts.error')
                    <div class="table-responsive">
                        <table id="datatable-page-index" class="table table-bordered">
                            <thead>
                            <tr>
                                <th>Kategori</th>
                                <th>Sayfa Başlığı</th>
                                <th>Görsel</th>
                                <th>Konum</th>
                                <th>Kısa Yazı</th>
                                <th>Durumu</th>
                                <th width="125px;">Tarih</th>
                                <th>İşlemler</th>
                            </tr>
                            </thead>


                            <tbody>
                            @foreach($pages as $page)
                            <tr>
                                <td>{{ $page->category->name }}</td>
                                <td>{{ $page->title }} <a href="{{url('./icerik/'.$page->category->slug.'/'.$page->slug)}}" target="_blank"><i class="pg-icon" style="font-size: 14px;">external_link</i></a> </td>
                                <td><img src="{!! $page->image !!}" style="height:50px;"></td>
                                <td>{{ $page->short_text }}</td>
                                <td>
                                @if($page->location == 0)
                                    SLİDER
                                    @elseif($page->location == 1)
                                    ORTA BÖLÜM
                                    @elseif($page->location == 2)
                                    TOPLU
                                    @elseif($page->location == 3)
                                    DEFAULT
                                    @endif
                                </td>
                                <td>{{ $page->active }}</td>
                                <td >{{ \Carbon\Carbon::parse($page->created_at)->format('d.m.Y H:i') }}</td>
                                <td>
                                    <a href="{{ route('web-pages.edit', createHashId($page->id)) }}" aria-label=""  class="text-success">
                                        <span>Düzenle</span>
                                    </a>
                                    <a href="javascript:void(0);" onclick="return confirmOpsDelete('{{ createHashId($page->id) }}')" role="menuitem" class="text-danger">
                                        <i class="pg-trash"></i> Sil
                                    </a>
                                    {{ Form::open([
                                        'method' => 'DELETE',
                                        'url' => route("web-pages.destroy", createHashId($page->id)),
                                        'id' => 'ops-delete-form-' . createHashId($page->id)
                                        ]) }}
                                    {{ Form::close() }}


                                </td>
                            </tr>
                            @endforeach

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <!-- END card -->
        </div>
        <!-- END CONTAINER FLUID -->
    </div>

@endsection